environment:
  matrix:
    # Python 2.7
    - PYTHON: "C:\\Python27"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7
    - PYTHON: "C:\\Python27-x64"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7

    # Python 3.4 -- this errors out with a bad checksum on QT (6/28/18). I don't want to deal with that
    #- PYTHON: "C:\\Python34"
    #  MINICONDA: C:\Miniconda3
    #  PYTHON_VERSION: 3.4
    #- PYTHON: "C:\\Python34-x64"
    #  DISTUTILS_USE_SDK: "1"
    #  MINICONDA: C:\Miniconda3
    #  PYTHON_VERSION: 3.4

    # Python 3.5
    - PYTHON: "C:\\Python35"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5
    - PYTHON: "C:\\Python35-x64"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5

    # Python 3.6
    - PYTHON: "C:\\Python36"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6
    - PYTHON: "C:\\Python36-x64"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6

    # Python 3.7
    - PYTHON: "C:\\Python37"
      MINICONDA: C:\Miniconda37
      PYTHON_VERSION: 3.7
    - PYTHON: "C:\\Python37-x64"
      MINICONDA: C:\Miniconda37
      PYTHON_VERSION: 3.7

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # We need to install numpy, scipy and matplotlib through conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION% msvc_runtime numpy scipy matplotlib nose"
  - activate test-environment
  # give me a remote-login option to debug
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
