environment:
  matrix:
    # Python 2.7
    - PYTHON: "C:\\Python27"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7
    - PYTHON: "C:\\Python27-x64"
      MINICONDA: C:\Miniconda
      PYTHON_VERSION: 2.7

    # Python 3.4
    - PYTHON: "C:\\Python34"
      MINICONDA: C:\Miniconda3
      PYTHON_VERSION: 3.4
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
      MINICONDA: C:\Miniconda3
      PYTHON_VERSION: 3.4

    # Python 3.5
    - PYTHON: "C:\\Python35"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5
    - PYTHON: "C:\\Python35-x64"
      MINICONDA: C:\Miniconda35
      PYTHON_VERSION: 3.5

    # Python 3.6
    - PYTHON: "C:\\Python36"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6
    - PYTHON: "C:\\Python36-x64"
      MINICONDA: C:\Miniconda36
      PYTHON_VERSION: 3.6

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # We need to install numpy, scipy and matplotlib through conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION% msvc_runtime numpy scipy matplotlib"
  - activate test-environment
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
  # this is how we test
  - "%PYTHON%\\python.exe -m pip install nose"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - "%PYTHON%\\python.exe setup.py test"

after_test:
  # this gives us stuff to play with
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
