language: python
python:
    #- '2.7'
    #- '3.5'
- '3.6'
  #- 3.7-dev

env:
    #- segyio_inc=false qt5_inc=false COVERALLS_PARALLEL=true
    #- segyio_inc=true qt5_inc=false COVERALLS_PARALLEL=true
    - segyio_inc=false qt5_inc=true COVERALLS_PARALLEL=true

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq

install:
- if [ "$segyio_inc" = true ] ; then pip install segyio; fi
- if [ "$qt5_inc" = true ] ; then bash install_qt.sh; fi
- pip install -r requirements.txt
- pip install coveralls
- pip install .

deploy:
  provider: pypi
  user: dlilien
  password:
    secure: DuqiQ+NBz4tTa+1Ej8wu7beC7xy2iOcRK5q63iMdYc2Qn6US1VW54rYiKUjEpn35XTwNRD/2zY5hqRn3GMWfoODE8pNS27gBnEtXQgg091ElHNXWXB261lkusslRLNVYd1iOPMOfl96YpZm9HipTwo0Npr0jLRMG8xbwletBkJRDXtZvrEhWIQ2CSfX5WWvx5IOKT65ZTsOxpzU4R7F0vrWE+J45e6doMsuSpMwNgtTdjh7RiCbB+FmQ0xmYk48r0DQ1optMsoLKaXfGLdhBDMbUhDEYHPDGZZARnTiBzR5Q1DdSYdoNTGqQwfiDKhePuh9g4eLw41MqXgzhdW/FI7FJtYBT5XLVhHCnPyRRkeC8E78V71Cz78fCSCIfhGVHGrOyHOUW3vq/3YYOuS/Ild4bocJdfONNQRqGBwUsrAIVnloSyEyvwQj0BexVX0huz9Tdx29vlpa04oKKEWND2qb1WUhO4uSk089WwLWVQzlCukA3GhkRzQ7OpUM1xyLvfSLskiOXnf8hvzH5TwMOFrl9bmsUPprzRNZ32fPP32lsiLazK9pIEIfHrptD6Bhaa1nQNMaiYQwpHvzGxYehHw0cRcYCtAm+/sMeO0ijBdbET+8GZe++5kbpIpZzcoT0xizteqwTUf0EPd+p+YcrfYwOLcmb4HzLffqkJy7LWcI=
  skip_existing: true
  distributions: "sdist bdist_wheel"

script: coverage run --source impdar --omit=impdar/tests/*,impdar/bin/*,impdar/gui/* setup.py test


after_success:
    coveralls

notifications:
      webhooks: https://coveralls.io/webhook
